import './globals.css';
import type { Metadata } from 'next';
import { Locale, i18n } from '@/i18n.config';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

import { Markazi_Text, Karla } from 'next/font/google';
const markazi = Markazi_Text({ subsets: ['latin'] });
const karla = Karla({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: Locale };
}) {
	return (
		<html lang={params.lang}>
			<body className={karla.className}>
				<Navbar lang={params.lang} />
				<main>{children}</main>
				<Footer lang={params.lang} />
			</body>
		</html>
	);
}
