import type { Metadata } from 'next';
import '../globals.css';
import { Locale, i18n } from '@/i18n.config';
import Navbar from './components/navbar';
import Footer from './components/footer';
import { karla } from '../fonts';

export const metadata: Metadata = {
	title: 'Little Llama | Pet Adoption Center',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: Locale };
}) {
	return (
		<html lang={params.lang}>
			<body className={karla.className}>
				<Navbar lang={params.lang} />
				<main>{children}</main>
				<Footer lang={params.lang} />
			</body>
		</html>
	);
}
